version: '3'
services:
    nginx:
        container_name: ${PROJECT_PREFIX}-nginx-latest
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./wwwroot:/usr/share/nginx/html
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx
    php-fpm:
        container_name: ${PROJECT_PREFIX}-php-5.6-fpm
        image: php:5.6-fpm
        volumes:
            - ./wwwroot:/www
            - ./php-fpm/conf:/usr/local/etc/php
            - ./php-fpm/logs:/usr/local/var/log
        environment:
            - ENV=prod
        env_file: ./.env
